### ISSUE TITLE
Performance improvement needed.

### ISSUE THREAD

**Issue by xingweitian** [opprop/checker-framework#103]
For Junit test:

typetools:
```
Testsuite: tests.NullnessFbcTest
Tests run: 15, Failures: 0, Skipped: 0, Time elapsed: 122.881 sec
```

opprop:
```
Testsuite: tests.NullnessFbcTest
Tests run: 15, Failures: 0, Skipped: 0, Time elapsed: 305.852 sec
```

For the other test suites in JUnit, opprop is also slower than typetools.

**Comment by lnsun** [comment]
Local tests on my desktop spent similar time with typetools.
Opprop: BUILD SUCCESSFUL in 16m 48s
Typetools: BUILD SUCCESSFUL in 17m 14s

**Comment by wmdietl** [comment]
@lnsun What target are you running?

When I run `./gradlew nullnessfbctest` on a JDK 11, I consistently get
with opprop:

```
> Task :checker:NullnessFbcTest
Testsuite: tests.NullnessFbcTest
Tests run: 15, Failures: 0, Skipped: 0, Time elapsed: 114.385 sec
```

with typetools:

```
> Task :checker:NullnessFbcTest
Testsuite: tests.NullnessFbcTest
Tests run: 15, Failures: 0, Skipped: 0, Time elapsed: 46.32 sec
```

They use the same stubparser and annotation-tools builds and there are no source differences between the two (I've commented out the changes in the ATF.)
I am baffled by what is going on.

I don't think #106 is the explanation, because I'm executing locally.

**Comment by xingweitian** [comment]
> @lnsun What target are you running?
> 
> When I run `./gradlew nullnessfbctest` on a JDK 11, I consistently get
> with opprop:
> 
> ```
> > Task :checker:NullnessFbcTest
> Testsuite: tests.NullnessFbcTest
> Tests run: 15, Failures: 0, Skipped: 0, Time elapsed: 114.385 sec
> ```
> 
> with typetools:
> 
> ```
> > Task :checker:NullnessFbcTest
> Testsuite: tests.NullnessFbcTest
> Tests run: 15, Failures: 0, Skipped: 0, Time elapsed: 46.32 sec
> ```
> 
> They use the same stubparser and annotation-tools builds and there are no source differences between the two (I've commented out the changes in the ATF.)
> I am baffled by what is going on.
> 
> I don't think #106 is the explanation, because I'm executing locally.

But after changing to use the docker image of typetools, the errors are indeed fixed...

**Comment by lnsun** [comment]
> @lnsun What target are you running?
> 
> When I run `./gradlew nullnessfbctest` on a JDK 11, I consistently get
> with opprop:
> 
> ```
> > Task :checker:NullnessFbcTest
> Testsuite: tests.NullnessFbcTest
> Tests run: 15, Failures: 0, Skipped: 0, Time elapsed: 114.385 sec
> ```
> 
> with typetools:
> 
> ```
> > Task :checker:NullnessFbcTest
> Testsuite: tests.NullnessFbcTest
> Tests run: 15, Failures: 0, Skipped: 0, Time elapsed: 46.32 sec
> ```
> 
> They use the same stubparser and annotation-tools builds and there are no source differences between the two (I've commented out the changes in the ATF.)
> I am baffled by what is going on.
> 
> I don't think #106 is the explanation, because I'm executing locally.

@wmdietl I was running `./gradlew allTests`.
For NullnessFbcTests, typetools consumed 61.457 sec, while opprop consumed 57.383 sec.

**Comment by xingweitian** [comment]
@wmdietl #106 passes all the Travis tests, I suggest to merge it, then many PRs in opprop/cf and opprop/downstream can be reviewed.

**Comment by wmdietl** [comment]
I tried with a clean checkout of opprop/master and now the timing is consistent with typetools/master.
I don't find a difference between these two clones, so this is still rather mysterious.
I've started looking at #106.
