### ISSUE TITLE
Try new CI

### ISSUE THREAD

**Issue by xingweitian** [opprop/checker-framework#107]
I tried github workflow as the CI and run `allTests`, it was so fast, only cost 20 min (Travis: 38 min).

Github workflow log in my own repo: https://github.com/xingweitian/checker-framework/commit/4db4c73cdffa0524fd0679a74dc20e442b733c40/checks?check_suite_id=314652463

Let's discuss if github workflow is a good choice.

**Comment by xingweitian** [comment]
We now use Azure Pipelines. This issue can be closed.

**Comment by wmdietl** [comment]
What are the differences between the Github CI and Azure Pipelines?

**Comment by xingweitian** [comment]
> What are the differences between the Github CI and Azure Pipelines?

Github CI is different from Azure Pipelines. It is invented by the Github. It also required to write some configuration files. For now, I think Azure Pipelines is great enough...
