### ISSUE TITLE
CI task inference_tests_jdk11 is failling on master

### ISSUE THREAD

**Issue by zcai1** [opprop/checker-framework#189]
Causes:
1. In docker image "mdernst/cf-ubuntu-jdk11:latest", module "lithium" is never available.
2. `import lithium` in https://github.com/opprop/do-like-javac/blob/3eb4a43521ae181a9b777a589e477b0c6ab7cb6e/do_like_javac/tools/testminimizer.py#L8
3. `git-clone-related kelloggm do-like-javac` in https://github.com/opprop/checker-framework/blob/6cccf27ebc5c99f2101c63763b0950a3db250fe8/checker/bin/wpi.sh#L262

Explanation:
CF uses kelloggm/do-like-javac which works well with all CF builds. Previously, "wpi.sh" clones do-like-javac from kelloggm with hardcoded address. `git-clone-related kelloggm do-like-javac`, however, will clone the do-like-javac in opprop because it has a branch named "master". The test didn't fail for our PR that made this change because opprop/do-like-javac doesn't have a branch named "eisop-3.17" (so it uses the default branch of kelloggm/do-like-javac).  Note that the file "testminimizer.py" doesn't exist in either kelloggm/do-like-javac or SRI-CSL/do-like-javac.

Depending on the purpose of having opprop/do-like-javac, there are several solutions:
1. Merge latest SRI-CSL/do-like-javac into opprop/do-like-javac
2. Change the "wpi.sh" script back to cloning the hardcoded kelloggm/do-like-javac repo
3. Remove opprop/do-like-javac if we no longer need it

**Comment by wmdietl** [comment]
@zcai1 Thanks for investigating this!

I've created https://github.com/opprop/do-like-javac/pull/18 which pulls in changes that should make the WPI test work.
Can you please try whether the version in that PR works, also for the CFI usages?

The testminimizer is an addition in this version which is documented in README_testminimizer.md. Could you make a PR that adds a reference to README_testminimizer.md from README.md?

Separately I will update the docker image to include lithium.

**Comment by Ao-senXiong** [comment]
Closed as this is outdated.
