### ISSUE TITLE
CI task plume_lib_jdk11 is failling on master

### ISSUE THREAD

**Issue by zcai1** [opprop/checker-framework#190]
Errors:
```
/tmp/options/src/main/java/org/plumelib/options/OptionsDoclet.java:562: error: [signature:argument.type.incompatible] incompatible argument for parameter arg0 of classNamed.
      ClassDoc optDoc = root.classNamed(oi.getDeclaringClass().getName());
                                                                      ^
  found   : @ClassGetName String
  required: @BinaryName String
/tmp/options/src/main/java/org/plumelib/options/OptionsDoclet.java:608: error: [signature:argument.type.incompatible] incompatible argument for parameter arg0 of classNamed.
    ClassDoc enumDoc = root.classNamed(oi.baseType.getName());
                                                          ^
  found   : @ClassGetName String
```

The cause is similar to https://github.com/opprop/checker-framework/issues/189: The PR build used plume-lib/options because we don't have a branch named "eisop-3.17" in opprop/options. However, the build for our master branch used opprop/options which is currently outdated.

This issue has already been fixed in the latest plume-lib/options, so I suggest merging the latest plume-lib/options into https://github.com/opprop/options.

**Comment by wmdietl** [comment]
I updated opprop/options but tests still fail
https://dev.azure.com/xingweitian/opprop-checkerframework/_build/results?buildId=510&view=logs&j=6d7f356d-b53b-5741-11e4-46348384314f&t=91bd2f1c-c8dc-5ccf-3911-504b875c6660&l=1283

Do you see why?

**Comment by zcai1** [comment]
> I updated opprop/options but tests still fail
> https://dev.azure.com/xingweitian/opprop-checkerframework/_build/results?buildId=510&view=logs&j=6d7f356d-b53b-5741-11e4-46348384314f&t=91bd2f1c-c8dc-5ccf-3911-504b875c6660&l=1283
> 
> Do you see why?

Now the issue is related to `git-clone-related plume-lib plume-util`, so I think we should also update https://github.com/opprop/plume-util

**Comment by wmdietl** [comment]
I moved all these different forks under https://github.com/eisop-plume-lib/ 
This issue should be resolved.
