### ISSUE TITLE
ant reformat creates a lot of modifications

### ISSUE THREAD

**Issue by JasonMrX** [opprop/checker-framework#29]
I had a clone version of the master branch but running `ant format` gives me a lot of modifications. Even after the reformat, I was still not able to commit due to 
`Improper formatting: checker/src/org/checkerframework/checker/lock/qual/PolyGuardedBy.java` 
Also, four untracted files are generated from the attempting to commit:

    checker/bin-devel/check-google-java-format.py
    checker/bin-devel/fixup-google-java-format.py
    checker/bin-devel/google-java-format-1.0-all-deps.jar
    checker/bin-devel/run-google-java-format.py

Any suggestions would be appreciated!

Jason

**Comment by wmdietl** [comment]
Sorry about the trouble!
I've created https://github.com/opprop/checker-framework/pull/30 to merge in the upstream changes to how formatting works.
Once they are merged, reapply your own changes. Commit should work again.

**Comment by wmdietl** [comment]
@JasonMrX I've updated from upstream. Let me know if this fixes the problems you had.

**Comment by JasonMrX** [comment]
@wmdietl Thanks a lot!
