### ISSUE TITLE
Trigger transitive downstream tests when testing CFI

### ISSUE THREAD

**Issue by jyluo** [opprop/checker-framework#81]
When making changes in CF, the travis downstream test only runs the basic test suite of CFI
https://github.com/opprop/checker-framework/blob/master/.travis-build.sh#L89

If the changes cause problems not in CFI but in CFI's downstream projects, travis currently does not report a failure. This should be updated to trigger and run all transitive downstream projects.

See PR https://github.com/opprop/checker-framework/pull/80 and corresponding CFI PR https://github.com/opprop/checker-framework-inference/pull/212

**Comment by Ao-senXiong** [comment]
Closed as already added in .ci-build.sh
